# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome-page-gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1118, 834)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 821, 151))
        self.label.setStyleSheet("font: 50pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54,54);")
        self.label.setObjectName("label")
        self.start_button = QtWidgets.QPushButton(Dialog)
        self.start_button.setGeometry(QtCore.QRect(950, 750, 93, 28))
        self.start_button.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(100, 100, 100);")
        self.start_button.setObjectName("start_button")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 911, 151))
        self.label_2.setStyleSheet("font: 50pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54, 54);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 300, 281, 101))
        self.label_3.setStyleSheet("font: 30pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54,54);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 390, 381, 71))
        self.label_4.setStyleSheet("font: 26pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54,54);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 480, 191, 51))
        self.label_5.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54,54);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 540, 331, 31))
        self.label_6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54,54);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 580, 311, 41))
        self.label_7.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54,54);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 630, 231, 41))
        self.label_8.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54,54);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 680, 321, 31))
        self.label_9.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(54, 54,54);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(740, 30, 311, 321))
        self.label_10.setStyleSheet("background-color: rgb(54, 54,54);")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("sharif-university-logo-1-600x593.png"))
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ECSP"))
        self.label.setText(_translate("Dialog", "Electric Circuits"))
        self.start_button.setText(_translate("Dialog", "Start"))
        self.label_2.setText(_translate("Dialog", "Software Project"))
        self.label_3.setText(_translate("Dialog", "Spring 2022"))
        self.label_4.setText(_translate("Dialog", "Professor : Dr. Hadi"))
        self.label_5.setText(_translate("Dialog", "Made By :"))
        self.label_6.setText(_translate("Dialog", "Mohammad Parsa Dini"))
        self.label_7.setText(_translate("Dialog", "Amir Hossein Naghdi"))
        self.label_8.setText(_translate("Dialog", "Ali Sadeghian"))
        self.label_9.setText(_translate("Dialog", "Amir Reza Tanevardi"))


#if __name__ == "__main__":
    #import sys
    #app = QtWidgets.QApplication(sys.argv)
    #Dialog = QtWidgets.QDialog()
    #ui = Ui_Dialog()
    #ui.setupUi(Dialog)
    #Dialog.show()
    # sys.exit(app.exec_())
